#!/usr/local/bin/ruby-1.9

require 'erb'
require 'fileutils'

HEADER = "      ## track: Open Chromatin (Signal)"

TABLES = %w(
wgEncodeDukeDNaseSeqSignalAosmcSerumfree
wgEncodeDukeDNaseSeqBaseOverlapSignalAosmcSerumfree
wgEncodeDukeDNaseSeqSignalChorion
wgEncodeDukeDNaseSeqBaseOverlapSignalChorion
wgEncodeDukeDNaseSeqSignalFibrobl
wgEncodeDukeDNaseSeqBaseOverlapSignalFibrobl
wgEncodeDukeDNaseSeqSignalFibrop
wgEncodeDukeDNaseSeqBaseOverlapSignalFibrop
wgEncodeDukeDNaseSeqSignalGm12878V2
wgEncodeDukeDNaseSeqBaseOverlapSignalGm12878V2
wgEncodeUncFAIREseqZinbaGm12878
wgEncodeUncFAIREseqSignalGm12878V2
wgEncodeUncFAIREseqBaseOverlapSignalGm12878V2
wgEncodeUtaChIPseqSignalGm12878CtcfV2
wgEncodeUtaChIPseqBaseOverlapSignalGm12878CtcfV2
wgEncodeUtaChIPseqSignalGm12878Cmyc
wgEncodeUtaChIPseqBaseOverlapSignalGm12878Cmyc
wgEncodeUtaChIPseqSignalGm12878Pol2
wgEncodeUtaChIPseqBaseOverlapSignalGm12878Pol2
wgEncodeUtaustinChIPseqSignalGm12878Input
wgEncodeDukeDNaseSeqSignalGm12891
wgEncodeDukeDNaseSeqBaseOverlapSignalGm12891
wgEncodeUtaChIPseqSignalGm12891Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalGm12891Ctcf
wgEncodeDukeDNaseSeqSignalGm12892
wgEncodeDukeDNaseSeqBaseOverlapSignalGm12892
wgEncodeUtaChIPseqSignalGm12892Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalGm12892Ctcf
wgEncodeDukeDNaseSeqSignalGm18507
wgEncodeDukeDNaseSeqBaseOverlapSignalGm18507
wgEncodeUncFAIREseqSignalGm18507
wgEncodeUncFAIREseqBaseOverlapSignalGm18507
wgEncodeDukeDNaseSeqSignalGm19238
wgEncodeDukeDNaseSeqBaseOverlapSignalGm19238
wgEncodeUtaChIPseqSignalGm19238Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalGm19238Ctcf
wgEncodeDukeDNaseSeqSignalGm19239
wgEncodeDukeDNaseSeqBaseOverlapSignalGm19239
wgEncodeUncFAIREseqSignalGm19239
wgEncodeUncFAIREseqBaseOverlapSignalGm19239
wgEncodeUtaChIPseqSignalGm19239Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalGm19239Ctcf
wgEncodeDukeDNaseSeqSignalGm19240
wgEncodeDukeDNaseSeqBaseOverlapSignalGm19240
wgEncodeUtaChIPseqSignalGm19240Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalGm19240Ctcf
wgEncodeDukeDNaseSeqSignalH1hesc
wgEncodeDukeDNaseSeqBaseOverlapSignalH1hesc
wgEncodeUncFAIREseqZinbaH1hesc
wgEncodeUncFAIREseqSignalH1hesc
wgEncodeUncFAIREseqBaseOverlapSignalH1hesc
wgEncodeUtaChIPseqSignalH1hescCtcf
wgEncodeUtaChIPseqBaseOverlapSignalH1hescCtcf
wgEncodeUtaChIPseqSignalH1hescCmyc
wgEncodeUtaChIPseqBaseOverlapSignalH1hescCmyc
wgEncodeUtaChIPseqSignalH1hescPol2
wgEncodeUtaChIPseqBaseOverlapSignalH1hescPol2
wgEncodeDukeDNaseSeqSignalH9es
wgEncodeDukeDNaseSeqBaseOverlapSignalH9es
wgEncodeDukeDNaseSeqSignalHelas3V2
wgEncodeDukeDNaseSeqBaseOverlapSignalHelas3V2
wgEncodeUncFAIREseqZinbaHelas3
wgEncodeUncFAIREseqSignalHelas3V2
wgEncodeUncFAIREseqBaseOverlapSignalHelas3V2
wgEncodeUtaChIPseqSignalHelas3CtcfV2
wgEncodeUtaChIPseqBaseOverlapSignalHelas3CtcfV2
wgEncodeUtaChIPseqSignalHelas3CmycV2
wgEncodeUtaChIPseqBaseOverlapSignalHelas3CmycV2
wgEncodeUtaChIPseqSignalHelas3Pol2
wgEncodeUtaChIPseqBaseOverlapSignalHelas3Pol2
wgEncodeUtaustinChIPseqSignalHelas3Input
wgEncodeDukeDNaseSeqSignalHelas3Ifna4h
wgEncodeDukeDNaseSeqBaseOverlapSignalHelas3Ifna4h
wgEncodeUncFAIREseqSignalHelas3Ifna4h
wgEncodeUncFAIREseqBaseOverlapSignalHelas3Ifna4h
wgEncodeUncFAIREseqSignalHelas3Ifng4h
wgEncodeUncFAIREseqBaseOverlapSignalHelas3Ifng4h
wgEncodeDukeDNaseSeqSignalHepg2V2
wgEncodeDukeDNaseSeqBaseOverlapSignalHepg2V2
wgEncodeUncFAIREseqZinbaHepg2
wgEncodeUncFAIREseqSignalHepg2V2
wgEncodeUncFAIREseqBaseOverlapSignalHepg2V2
wgEncodeUtaChIPseqSignalHepg2CtcfV2
wgEncodeUtaChIPseqBaseOverlapSignalHepg2CtcfV2
wgEncodeUtaChIPseqSignalHepg2CmycV2
wgEncodeUtaChIPseqBaseOverlapSignalHepg2CmycV2
wgEncodeUtaChIPseqSignalHepg2Pol2
wgEncodeUtaChIPseqBaseOverlapSignalHepg2Pol2
wgEncodeUtaustinChIPseqSignalHepg2Input
wgEncodeDukeDNaseSeqSignalHsmm
wgEncodeDukeDNaseSeqBaseOverlapSignalHsmm
wgEncodeDukeDNaseSeqSignalHsmmt
wgEncodeDukeDNaseSeqBaseOverlapSignalHsmmt
wgEncodeDukeDNaseSeqSignalHuvec
wgEncodeDukeDNaseSeqBaseOverlapSignalHuvec
wgEncodeUncFAIREseqZinbaHuvec
wgEncodeUncFAIREseqSignalHuvec
wgEncodeUncFAIREseqBaseOverlapSignalHuvec
wgEncodeUtaChIPseqSignalHuvecCtcf
wgEncodeUtaChIPseqBaseOverlapSignalHuvecCtcf
wgEncodeUtaChIPseqSignalHuvecCmyc
wgEncodeUtaChIPseqBaseOverlapSignalHuvecCmyc
wgEncodeUtaChIPseqSignalHuvecPol2
wgEncodeUtaChIPseqBaseOverlapSignalHuvecPol2
wgEncodeUtaustinChIPseqSignalHuvecInput
wgEncodeDukeDNaseSeqSignalK562V2
wgEncodeDukeDNaseSeqBaseOverlapSignalK562V2
wgEncodeUncFAIREseqZinbaK562
wgEncodeUncFAIREseqSignalK562V2
wgEncodeUncFAIREseqBaseOverlapSignalK562V2
wgEncodeUtaChIPseqSignalK562CtcfV2
wgEncodeUtaChIPseqBaseOverlapSignalK562CtcfV2
wgEncodeUtaChIPseqSignalK562CmycV2
wgEncodeUtaChIPseqBaseOverlapSignalK562CmycV2
wgEncodeUtaChIPseqSignalK562Pol2
wgEncodeUtaChIPseqBaseOverlapSignalK562Pol2
wgEncodeUtaustinChIPseqSignalK562Input
wgEncodeDukeDNaseSeqSignalLhsr
wgEncodeDukeDNaseSeqBaseOverlapSignalLhsr
wgEncodeUncFAIREseqSignalLhsr
wgEncodeUncFAIREseqBaseOverlapSignalLhsr
wgEncodeDukeDNaseSeqSignalLhsrAndro
wgEncodeDukeDNaseSeqBaseOverlapSignalLhsrAndro
wgEncodeUncFAIREseqSignalLhsrAndro
wgEncodeUncFAIREseqBaseOverlapSignalLhsrAndro
wgEncodeDukeDNaseSeqSignalMcf7
wgEncodeDukeDNaseSeqBaseOverlapSignalMcf7
wgEncodeUtaChIPseqSignalMcf7Ctcf
wgEncodeUtaChIPseqBaseOverlapSignalMcf7Ctcf
wgEncodeUtaChIPseqSignalMcf7Cmyc
wgEncodeUtaChIPseqBaseOverlapSignalMcf7Cmyc
wgEncodeUtaustinChIPseqSignalMcf7
wgEncodeDukeDNaseSeqSignalMedullo
wgEncodeDukeDNaseSeqBaseOverlapSignalMedullo
wgEncodeDukeDNaseSeqSignalMelano
wgEncodeDukeDNaseSeqBaseOverlapSignalMelano
wgEncodeDukeDNaseSeqSignalMyometr
wgEncodeDukeDNaseSeqBaseOverlapSignalMyometr
wgEncodeUncFAIREseqSignalNhbe
wgEncodeUncFAIREseqBaseOverlapSignalNhbe
wgEncodeDukeDNaseSeqSignalNhek
wgEncodeDukeDNaseSeqBaseOverlapSignalNhek
wgEncodeUncFAIREseqZinbaNhek
wgEncodeUncFAIREseqSignalNhek
wgEncodeUncFAIREseqBaseOverlapSignalNhek
wgEncodeUtaChIPseqSignalNhekCtcf
wgEncodeUtaChIPseqBaseOverlapSignalNhekCtcf
wgEncodeDukeDNaseSeqSignalPanislets
wgEncodeDukeDNaseSeqBaseOverlapSignalPanislets
wgEncodeUncFAIREseqSignalPanislets
wgEncodeUncFAIREseqBaseOverlapSignalPanislets
wgEncodeDukeDNaseSeqSignalProgfib
wgEncodeDukeDNaseSeqBaseOverlapSignalProgfib
wgEncodeUtaChIPseqSignalProgfibCtcf
wgEncodeUtaChIPseqBaseOverlapSignalProgfibCtcf
wgEncodeUtaChIPseqSignalProgfibPol2
wgEncodeUtaChIPseqBaseOverlapSignalProgfibPol2
wgEncodeUtaustinChIPseqSignalProgfib
)

temp_spec = "template_spec.txt"
temp_auto = "template_auto.txt"
temp_main = "template_main.txt"

FileUtils.mkdir_p("Specs") unless FileTest.exist?("Specs")
FileUtils.mkdir_p("Libs") unless FileTest.exist?("Libs")

TABLES.each do |tab|
  table_name  = tab
  klass_name  = tab[0].upcase << tab[1..-1]
  script_name = tab.downcase

  open("Specs/#{script_name}_spec.rb", "w") do |writer|
    erb = ERB.new File.read(temp_spec)
    writer.puts erb.result binding
  end

  open("Libs/#{script_name}.rb", "w") do |writer|
    erb = ERB.new File.read(temp_main)
    writer.puts erb.result binding
  end

end

open("autoload_snippet.rb", 'w') do |writer|
  writer.puts HEADER
  TABLES.each do |tab|
    table_name  = tab
    klass_name  = tab[0].upcase << tab[1..-1]
    script_name = tab.downcase
    erb = ERB.new File.read(temp_auto)
    writer.puts erb.result binding
  end
end
