#!/usr/local/bin/ruby-1.9

require 'erb'
require 'fileutils'

HEADER = "      ## track: GIS PET Loc"

TABLES = %w(
wgEncodeGisPetPlusRawSigRep1Gm12878CytosolLongpolya
wgEncodeGisPetPlusRawSigRep2Gm12878CytosolLongpolya
wgEncodeGisPetMinusRawSigRep1Gm12878CytosolLongpolya
wgEncodeGisPetMinusRawSigRep2Gm12878CytosolLongpolya
wgEncodeGisPetAlignmentsRep1Gm12878CytosolLongpolya
wgEncodeGisPetAlignmentsRep2Gm12878CytosolLongpolya
wgEncodeGisPetClustersRep1Gm12878CytosolPap
wgEncodeGisPetClustersRep2Gm12878CytosolPap
wgEncodeGisPetPlusRawSigRep1Gm12878NucleusLongpolya
wgEncodeGisPetMinusRawSigRep1Gm12878NucleusLongpolya
wgEncodeGisPetAlignmentsRep1Gm12878NucleusLongpolya
wgEncodeGisPetClustersRep1Gm12878NucleusPap
wgEncodeGisPetPlusRawSigRep1H1hescCellLongpolya
wgEncodeGisPetMinusRawSigRep1H1hescCellLongpolya
wgEncodeGisPetAlignmentsRep1H1hescCellLongpolya
wgEncodeGisPetClustersRep1H1hescCellPap
wgEncodeGisPetPlusRawSignalRep1HuvecCytosolLongpolya
wgEncodeGisPetMinusRawSignalRep1HuvecCytosolLongpolya
wgEncodeGisPetAlignmentsRep1HuvecCytosolLongpolya
wgEncodeGisPetClustersRep1HuvecCytosolPap
wgEncodeGisPetPlusRawSigRep1HuvecNucleusLongpolya
wgEncodeGisPetMinusRawSigRep1HuvecNucleusLongpolya
wgEncodeGisPetAlignmentsRep1HuvecNucleusLongpolya
wgEncodeGisPetClustersRep1HuvecNucleusPap
wgEncodeGisPetPlusRawSignalRep1Helas3CytosolLongpolya
wgEncodeGisPetMinusRawSignalRep1Helas3CytosolLongpolya
wgEncodeGisPetAlignmentsRep1Helas3CytosolLongpolya
wgEncodeGisPetClustersRep1Helas3CytosolPap
wgEncodeGisPetPlusRawSignalRep1Helas3NucleusLongpolya
wgEncodeGisPetMinusRawSignalRep1Helas3NucleusLongpolya
wgEncodeGisPetAlignmentsRep1Helas3NucleusLongpolya
wgEncodeGisPetClustersRep1Helas3NucleusPap
wgEncodeGisPetPlusRawSigRep1Hepg2CytosolLongpolya
wgEncodeGisPetMinusRawSigRep1Hepg2CytosolLongpolya
wgEncodeGisPetAlignmentsRep1Hepg2CytosolLongpolya
wgEncodeGisPetClustersRep1Hepg2CytosolPap
wgEncodeGisPetPlusRawSigRep1Hepg2NucleusLongpolya
wgEncodeGisPetMinusRawSigRep1Hepg2NucleusLongpolya
wgEncodeGisPetAlignmentsRep1Hepg2NucleusLongpolya
wgEncodeGisPetClustersRep1Hepg2NucleusPap
wgEncodeGisPetPlusRawSigRep1K562PolysomeLongpolya
wgEncodeGisPetMinusRawSigRep1K562PolysomeLongpolya
wgEncodeGisPetAlignmentsRep1K562PolysomeLongpolya
wgEncodeGisPetClustersRep1K562PolysomePap
wgEncodeGisPetPlusRawSigRep1K562CytosolLongpolya
wgEncodeGisPetPlusRawSigRep2K562CytosolLongpolya
wgEncodeGisPetMinusRawSigRep1K562CytosolLongpolya
wgEncodeGisPetMinusRawSigRep2K562CytosolLongpolya
wgEncodeGisPetAlignmentsRep1K562CytosolLongpolya
wgEncodeGisPetAlignmentsRep2K562CytosolLongpolya
wgEncodeGisPetClustersRep1K562CytosolPap
wgEncodeGisPetClustersRep2K562CytosolPap
wgEncodeGisPetPlusRawSigRep1K562NucleusLongpolya
wgEncodeGisPetMinusRawSigRep1K562NucleusLongpolya
wgEncodeGisPetAlignmentsRep1K562NucleusLongpolya
wgEncodeGisPetClustersRep1K562NucleusPap
wgEncodeGisPetPlusRawSigRep1K562NucleoplasmTotal
wgEncodeGisPetMinusRawSigRep1K562NucleoplasmTotal
wgEncodeGisPetAlignmentsRep1K562NucleoplasmTotal
wgEncodeGisPetClustersRep1K562NucleoplasmTotal
wgEncodeGisPetPlusRawSigRep1K562ChromatinTotal
wgEncodeGisPetMinusRawSigRep1K562ChromatinTotal
wgEncodeGisPetAlignmentsRep1K562ChromatinTotal
wgEncodeGisPetClustersRep1K562ChromatinTotal
wgEncodeGisPetPlusRawSigRep1K562NucleolusTotal
wgEncodeGisPetMinusRawSigRep1K562NucleolusTotal
wgEncodeGisPetAlignmentsRep1K562NucleolusTotal
wgEncodeGisPetClustersRep1K562NucleolusTotal
wgEncodeGisPetPlusRawSigRep1NhekCytosolLongpolya
wgEncodeGisPetMinusRawSigRep1NhekCytosolLongpolya
wgEncodeGisPetAlignmentsRep1NhekCytosolLongpolya
wgEncodeGisPetClustersRep1NhekCytosolPap
wgEncodeGisPetPlusRawSigRep1NhekNucleusLongpolya
wgEncodeGisPetMinusRawSigRep1NhekNucleusLongpolya
wgEncodeGisPetAlignmentsRep1NhekNucleusLongpolya
wgEncodeGisPetClustersRep1NhekNucleusPap
wgEncodeGisPetPlusRawSigRep1ProstateCellLongpolya
wgEncodeGisPetMinusRawSigRep1ProstateCellLongpolya
wgEncodeGisPetAlignmentsRep1ProstateCellLongpolya
wgEncodeGisPetClustersRep1ProstateCellPap
)

temp_spec = "template_spec.txt"
temp_auto = "template_auto.txt"
temp_main = "template_main.txt"

FileUtils.mkdir_p("Specs") unless FileTest.exist?("Specs")
FileUtils.mkdir_p("Libs") unless FileTest.exist?("Libs")

TABLES.each do |tab|
  table_name  = tab
  klass_name  = tab[0].upcase << tab[1..-1]
  script_name = tab.downcase

  open("Specs/#{script_name}_spec.rb", "w") do |writer|
    erb = ERB.new File.read(temp_spec)
    writer.puts erb.result binding
  end

  open("Libs/#{script_name}.rb", "w") do |writer|
    erb = ERB.new File.read(temp_main)
    writer.puts erb.result binding
  end

end

open("autoload_snippet.rb", 'w') do |writer|
  writer.puts HEADER
  TABLES.each do |tab|
    table_name  = tab
    klass_name  = tab[0].upcase << tab[1..-1]
    script_name = tab.downcase
    erb = ERB.new File.read(temp_auto)
    writer.puts erb.result binding
  end
end
