# -*- coding: utf-8 -*-
# = hg19/eiojcvinaspos.rb
# Copyright::
#  Copyright (C) 2011 MISHIMA, Hiroyuki <missy at be.to / hmishima at nagasaki-u.ac.jp> 
# License::     The Ruby licence (Ryby's / GPLv2 dual)
#
# = Table desfription in UCSC Table Browser 
# Genes in metazoa are controlled by a complex array of cis-regulatory
# elements that include core and distal promoters, enhancers,
# insulators, silencers, etc. (Levine and Tjian, 2003). In living
# cells, functionally active cis-regulatory elements bear a unifying
# feature, which is a chromatin-based epigenetic signature known as
# nuclease hypersensitivity (Elgin, 1988; Gross and Garrard, 1988;
# Wolffe, 1998). This track presents the results of a collaboration
# between J. Craig Venter Institute (JCVI, Rockville MD) and the
# European Institute of Oncology (Milan, Italy) to isolate nuclease
# accessible sites (NAS) from primary human CD34+ hematopoietic stem
# and progenitor cells, and from CD34- cells, maturating myeloid cells
# generated by in vitro differentiation of CD34+ cells (Gargiulo et
# al., submitted). This effort made use of a method (originally
# developed at Sangamo BioSciences, Richmond, CA) to isolate such NAS
# from living cells using restriction enzymes (RE), leading to
# minimal, if any, contamination from bulk DNA. High throughput 454
# sequencing was then used to generate NAS libraries in CD34+ and
# CD34- cells: this technology has been named "NA-Seq" (Gargiulo et
# al., submitted). 
#
# = ommitted dynamic method(s) due to the method name collision
#  none

module Bio
  module Ucsc
    module Hg19
      class EioJcviNASPos < DBConnection
        extend Bio::Ucsc::Hg19::QueryUsingChromBin
        set_table_name 'eioJcviNASPos'
        set_primary_key nil
      end 
    end # module Hg19
  end # module Ucsc
end # Bio
