      ## track: Stanf Promoter
      autoload :EncodeStanfordPromotersAGS, "#{base}/encodestanfordpromotersags"
      autoload :EncodeStanfordPromotersBe2C, "#{base}/encodestanfordpromotersbe2c"
      autoload :EncodeStanfordPromotersCRL1690, "#{base}/encodestanfordpromoterscrl1690"
      autoload :EncodeStanfordPromotersG402, "#{base}/encodestanfordpromotersg402"
      autoload :EncodeStanfordPromotersHCT116, "#{base}/encodestanfordpromotershct116"
      autoload :EncodeStanfordPromotersHMCB, "#{base}/encodestanfordpromotershmcb"
      autoload :EncodeStanfordPromotersHT1080, "#{base}/encodestanfordpromotersht1080"
      autoload :EncodeStanfordPromotersHTB11, "#{base}/encodestanfordpromotershtb11"
      autoload :EncodeStanfordPromotersHela, "#{base}/encodestanfordpromotershela"
      autoload :EncodeStanfordPromotersHepG2, "#{base}/encodestanfordpromotershepg2"
      autoload :EncodeStanfordPromotersJEG3, "#{base}/encodestanfordpromotersjeg3"
      autoload :EncodeStanfordPromotersMG63, "#{base}/encodestanfordpromotersmg63"
      autoload :EncodeStanfordPromotersMRC5, "#{base}/encodestanfordpromotersmrc5"
      autoload :EncodeStanfordPromotersPanc1, "#{base}/encodestanfordpromoterspanc1"
      autoload :EncodeStanfordPromotersSnu182, "#{base}/encodestanfordpromoterssnu182"
      autoload :EncodeStanfordPromotersU87, "#{base}/encodestanfordpromotersu87"
      autoload :EncodeStanfordPromotersAverage, "#{base}/encodestanfordpromotersaverage"
