      ## track: Duke/NHGRI DNase
      autoload :EncodeNhgriDnaseHsChipRawGm06990, "#{base}/encodenhgridnasehschiprawgm06990"
      autoload :EncodeNhgriDnaseHsChipRawCd4, "#{base}/encodenhgridnasehschiprawcd4"
      autoload :EncodeNhgriDnaseHsChipRawHela, "#{base}/encodenhgridnasehschiprawhela"
      autoload :EncodeNhgriDnaseHsChipRawHepG2, "#{base}/encodenhgridnasehschiprawhepg2"
      autoload :EncodeNhgriDnaseHsChipRawH9, "#{base}/encodenhgridnasehschiprawh9"
      autoload :EncodeNhgriDnaseHsChipRawImr90, "#{base}/encodenhgridnasehschiprawimr90"
      autoload :EncodeNhgriDnaseHsChipRawK562, "#{base}/encodenhgridnasehschiprawk562"
      autoload :EncodeNhgriDnaseHsChipPvalGm06990, "#{base}/encodenhgridnasehschippvalgm06990"
      autoload :EncodeNhgriDnaseHsChipPvalCd4, "#{base}/encodenhgridnasehschippvalcd4"
      autoload :EncodeNhgriDnaseHsChipPvalHela, "#{base}/encodenhgridnasehschippvalhela"
      autoload :EncodeNhgriDnaseHsChipPvalHepG2, "#{base}/encodenhgridnasehschippvalhepg2"
      autoload :EncodeNhgriDnaseHsChipPvalH9, "#{base}/encodenhgridnasehschippvalh9"
      autoload :EncodeNhgriDnaseHsChipPvalImr90, "#{base}/encodenhgridnasehschippvalimr90"
      autoload :EncodeNhgriDnaseHsChipPvalK562, "#{base}/encodenhgridnasehschippvalk562"
      autoload :EncodeNhgriDnaseHsMpssCd4, "#{base}/encodenhgridnasehsmpsscd4"
      autoload :EncodeNhgriDnaseHsMpssCd4Act, "#{base}/encodenhgridnasehsmpsscd4act"
