      ## track: RIKEN CAGE Loc
      autoload :AffyTxnPhase3FragsHDF, "#{base}/affytxnphase3fragshdf"
      autoload :AffyTxnPhase3FragsHeLaCyto, "#{base}/affytxnphase3fragshelacyto"
      autoload :AffyTxnPhase3FragsHeLaNuclear, "#{base}/affytxnphase3fragshelanuclear"
      autoload :AffyTxnPhase3FragsHepG2Cyto, "#{base}/affytxnphase3fragshepg2cyto"
      autoload :AffyTxnPhase3FragsHepG2Nuclear, "#{base}/affytxnphase3fragshepg2nuclear"
      autoload :AffyTxnPhase3FragsJurkat, "#{base}/affytxnphase3fragsjurkat"
      autoload :AffyTxnPhase3FragsNCCIT, "#{base}/affytxnphase3fragsnccit"
      autoload :AffyTxnPhase3FragsPC3, "#{base}/affytxnphase3fragspc3"
      autoload :AffyTxnPhase3FragsSK, "#{base}/affytxnphase3fragssk"
      autoload :AffyTxnPhase3FragsU87MG, "#{base}/affytxnphase3fragsu87mg"
