      ## track: Gencode RACEfrags
      autoload :EncodeGencodeRaceFragsPrimer, "#{base}/encodegencoderacefragsprimer"
      autoload :EncodeGencodeRaceFragsBrain, "#{base}/encodegencoderacefragsbrain"
      autoload :EncodeGencodeRaceFragsColon, "#{base}/encodegencoderacefragscolon"
      autoload :EncodeGencodeRaceFragsHeart, "#{base}/encodegencoderacefragsheart"
      autoload :EncodeGencodeRaceFragsKidney, "#{base}/encodegencoderacefragskidney"
      autoload :EncodeGencodeRaceFragsLiver, "#{base}/encodegencoderacefragsliver"
      autoload :EncodeGencodeRaceFragsLung, "#{base}/encodegencoderacefragslung"
      autoload :EncodeGencodeRaceFragsMuscle, "#{base}/encodegencoderacefragsmuscle"
      autoload :EncodeGencodeRaceFragsPlacenta, "#{base}/encodegencoderacefragsplacenta"
      autoload :EncodeGencodeRaceFragsSmallIntest, "#{base}/encodegencoderacefragssmallintest"
      autoload :EncodeGencodeRaceFragsSpleen, "#{base}/encodegencoderacefragsspleen"
      autoload :EncodeGencodeRaceFragsStomach, "#{base}/encodegencoderacefragsstomach"
      autoload :EncodeGencodeRaceFragsTestis, "#{base}/encodegencoderacefragstestis"
      autoload :EncodeGencodeRaceFragsGM06990, "#{base}/encodegencoderacefragsgm06990"
      autoload :EncodeGencodeRaceFragsHL60, "#{base}/encodegencoderacefragshl60"
      autoload :EncodeGencodeRaceFragsHela, "#{base}/encodegencoderacefragshela"
