#!/usr/local/bin/ruby-1.9

require 'erb'
require 'fileutils'

HEADER = "      ## track: RIKEN CAGE Loc"

TABLES = %w(
wgEncodeUwAffyExonArraySimpleSignalRep1Gm12878
wgEncodeUwAffyExonArraySimpleSignalRep1K562V2
wgEncodeUwAffyExonArraySimpleSignalRep2K562
wgEncodeUwAffyExonArraySimpleSignalRep1Helas3
wgEncodeUwAffyExonArraySimpleSignalRep2Helas3V2
wgEncodeUwAffyExonArraySimpleSignalRep1Hepg2
wgEncodeUwAffyExonArraySimpleSignalRep2Hepg2
wgEncodeUwAffyExonArraySimpleSignalRep1Huvec
wgEncodeUwAffyExonArraySimpleSignalRep1Ag04449
wgEncodeUwAffyExonArraySimpleSignalRep2Ag04449
wgEncodeUwAffyExonArraySimpleSignalRep1Ag04450
wgEncodeUwAffyExonArraySimpleSignalRep2Ag04450
wgEncodeUwAffyExonArraySimpleSignalRep1Ag09309
wgEncodeUwAffyExonArraySimpleSignalRep2Ag09309
wgEncodeUwAffyExonArraySimpleSignalRep1Ag09319
wgEncodeUwAffyExonArraySimpleSignalRep2Ag09319
wgEncodeUwAffyExonArraySimpleSignalRep1Ag10803
wgEncodeUwAffyExonArraySimpleSignalRep2Ag10803
wgEncodeUwAffyExonArraySimpleSignalRep1Bjtert
wgEncodeUwAffyExonArraySimpleSignalRep2Bjtert
wgEncodeUwAffyExonArraySimpleSignalRep1Cmk
wgEncodeUwAffyExonArraySimpleSignalRep1Caco2
wgEncodeUwAffyExonArraySimpleSignalRep2Caco2
wgEncodeUwAffyExonArraySimpleSignalRep1Gm06990
wgEncodeUwAffyExonArraySimpleSignalRep2Gm06990
wgEncodeUwAffyExonArraySimpleSignalRep1H7es
wgEncodeUwAffyExonArraySimpleSignalRep1Hae
wgEncodeUwAffyExonArraySimpleSignalRep2Hae
wgEncodeUwAffyExonArraySimpleSignalRep1Hcf
wgEncodeUwAffyExonArraySimpleSignalRep2Hcf
wgEncodeUwAffyExonArraySimpleSignalRep1Hcm
wgEncodeUwAffyExonArraySimpleSignalRep2Hcm
wgEncodeUwAffyExonArraySimpleSignalRep1Hcpe
wgEncodeUwAffyExonArraySimpleSignalRep2Hcpe
wgEncodeUwAffyExonArraySimpleSignalRep1Hee
wgEncodeUwAffyExonArraySimpleSignalRep2Hee
wgEncodeUwAffyExonArraySimpleSignalRep1Hipe
wgEncodeUwAffyExonArraySimpleSignalRep2Hipe
wgEncodeUwAffyExonArraySimpleSignalRep1Hmec
wgEncodeUwAffyExonArraySimpleSignalRep1Hnpce
wgEncodeUwAffyExonArraySimpleSignalRep2Hnpce
wgEncodeUwAffyExonArraySimpleSignalRep1Hrcepic
wgEncodeUwAffyExonArraySimpleSignalRep2Hrcepic
wgEncodeUwAffyExonArraySimpleSignalRep1Hre
wgEncodeUwAffyExonArraySimpleSignalRep2Hre
wgEncodeUwAffyExonArraySimpleSignalRep1Hrpe
wgEncodeUwAffyExonArraySimpleSignalRep2Hrpe
wgEncodeUwAffyExonArraySimpleSignalRep1Jurkat
wgEncodeUwAffyExonArraySimpleSignalRep2Jurkat
wgEncodeUwAffyExonArraySimpleSignalRep1Mcf7
wgEncodeUwAffyExonArraySimpleSignalRep2Mcf7
wgEncodeUwAffyExonArraySimpleSignalRep1Nb4V2
wgEncodeUwAffyExonArraySimpleSignalRep2Nb4
wgEncodeUwAffyExonArraySimpleSignalRep1Nhdfneo
wgEncodeUwAffyExonArraySimpleSignalRep2Nhdfneo
wgEncodeUwAffyExonArraySimpleSignalRep1Nhek
wgEncodeUwAffyExonArraySimpleSignalRep1Nhlf
wgEncodeUwAffyExonArraySimpleSignalRep2Nhlf
wgEncodeUwAffyExonArraySimpleSignalRep1Panc1
wgEncodeUwAffyExonArraySimpleSignalRep2Panc1
wgEncodeUwAffyExonArraySimpleSignalRep1Saec
wgEncodeUwAffyExonArraySimpleSignalRep2Saec
wgEncodeUwAffyExonArraySimpleSignalRep1SkmcV2
wgEncodeUwAffyExonArraySimpleSignalRep2Skmc
wgEncodeUwAffyExonArraySimpleSignalRep1Sknshra
wgEncodeUwAffyExonArraySimpleSignalRep2Sknshra
wgEncodeUwAffyExonArraySimpleSignalRep1Th1
)

temp_spec = "template_spec.txt"
temp_auto = "template_auto.txt"
temp_main = "template_main.txt"

FileUtils.mkdir_p("Specs") unless FileTest.exist?("Specs")
FileUtils.mkdir_p("Libs") unless FileTest.exist?("Libs")

TABLES.each do |tab|
  table_name  = tab
  klass_name  = tab[0].upcase << tab[1..-1]
  script_name = tab.downcase

  open("Specs/#{script_name}_spec.rb", "w") do |writer|
    erb = ERB.new File.read(temp_spec)
    writer.puts erb.result binding
  end

  open("Libs/#{script_name}.rb", "w") do |writer|
    erb = ERB.new File.read(temp_main)
    writer.puts erb.result binding
  end

end

open("autoload_snippet.rb", 'w') do |writer|
  writer.puts HEADER
  TABLES.each do |tab|
    table_name  = tab
    klass_name  = tab[0].upcase << tab[1..-1]
    script_name = tab.downcase
    erb = ERB.new File.read(temp_auto)
    writer.puts erb.result binding
  end
end
