      ## track: Enhanced H3K4Me3
      autoload :WgEncodeBroadChipSeqSignalGm12878H3k4me3, "#{base}/wgencodebroadchipseqsignalgm12878h3k4me3"
      autoload :WgEncodeBroadChipSeqSignalH1hescH3k4me3, "#{base}/wgencodebroadchipseqsignalh1hesch3k4me3"
      autoload :WgEncodeBroadChipSeqSignalHepg2H3k4me3, "#{base}/wgencodebroadchipseqsignalhepg2h3k4me3"
      autoload :WgEncodeBroadChipSeqSignalHmecH3k4me3, "#{base}/wgencodebroadchipseqsignalhmech3k4me3"
      autoload :WgEncodeBroadChipSeqSignalHsmmH3k4me3, "#{base}/wgencodebroadchipseqsignalhsmmh3k4me3"
      autoload :WgEncodeBroadChipSeqSignalHuvecH3k4me3, "#{base}/wgencodebroadchipseqsignalhuvech3k4me3"
      autoload :WgEncodeBroadChipSeqSignalK562H3k4me3, "#{base}/wgencodebroadchipseqsignalk562h3k4me3"
      autoload :WgEncodeBroadChipSeqSignalNhekH3k4me3, "#{base}/wgencodebroadchipseqsignalnhekh3k4me3"
      autoload :WgEncodeBroadChipSeqSignalNhlfH3k4me3, "#{base}/wgencodebroadchipseqsignalnhlfh3k4me3"
