# -*- coding: utf-8 -*-
# = hg19/wgencodegen2wayconspseudov4.rb
# Copyright::
#  Copyright (C) 2011 MISHIMA, Hiroyuki <missy at be.to / hmishima at nagasaki-u.ac.jp> 
# License::     The Ruby licence (Ryby's / GPLv2 dual)
#
# = Table desfription in UCSC Table Browser 
# The Gencode Genes track (version 4, May 2010) shows high-quality
# manual annotations merged with evidence-based automated annotations
# across the entire human genome generated by the GENCODE project. The
# Gencode gene set presents a full merge between HAVANA and
# ENSEMBL. Priority is given to the manually curated HAVANA
# annotation, using predicted ENSEMBL annotations when there are no
# corresponding manual annotations. The annotation was carried out on
# genome assembly GRCh37 (hg19).
#
# = ommitted dynamic method(s) due to the method name collision
#  none

module Bio
  module Ucsc
    module Hg19
      class WgEncodeGencode2wayConsPseudoV4 < DBConnection
        extend Bio::Ucsc::Hg19::QueryUsingTxBin
        set_table_name 'wgEncodeGencodePolyaV4'
        set_primary_key nil
      end 
    end # module Hg19
  end # module Ucsc
end # Bio
