      ## track: UW DNAse-QCP
      autoload :EncodeUWRegulomeBaseCD4, "#{base}/encodeuwregulomebasecd4"
      autoload :EncodeUWRegulomeBaseCaCo2, "#{base}/encodeuwregulomebasecaco2"
      autoload :EncodeUWRegulomeBaseCaLU3, "#{base}/encodeuwregulomebasecalu3"
      autoload :EncodeUWRegulomeBaseEryAdult, "#{base}/encodeuwregulomebaseeryadult"
      autoload :EncodeUWRegulomeBaseEryFetal, "#{base}/encodeuwregulomebaseeryfetal"
      autoload :EncodeUWRegulomeBaseGM, "#{base}/encodeuwregulomebasegm"
      autoload :EncodeUWRegulomeBaseHMEC, "#{base}/encodeuwregulomebasehmec"
      autoload :EncodeUWRegulomeBaseHRE, "#{base}/encodeuwregulomebasehre"
      autoload :EncodeUWRegulomeBaseHeLa, "#{base}/encodeuwregulomebasehela"
      autoload :EncodeUWRegulomeBaseHepG2, "#{base}/encodeuwregulomebasehepg2"
      autoload :EncodeUWRegulomeBaseHuh7, "#{base}/encodeuwregulomebasehuh7"
      autoload :EncodeUWRegulomeBaseK562, "#{base}/encodeuwregulomebasek562"
      autoload :EncodeUWRegulomeBaseNHBE, "#{base}/encodeuwregulomebasenhbe"
      autoload :EncodeUWRegulomeBasePANC, "#{base}/encodeuwregulomebasepanc"
      autoload :EncodeUWRegulomeBaseSAEC, "#{base}/encodeuwregulomebasesaec"
      autoload :EncodeUWRegulomeBaseSKnSH, "#{base}/encodeuwregulomebasesknsh"
