      ## track: RIKEN CAGE  Loc Aligns
      autoload :WgEncodeRikenCageAlignmentsGm12878NucleolusTotal, "#{base}/wgencoderikencagealignmentsgm12878nucleolustotal"
      autoload :WgEncodeRikenCageAlignmentsH1hescCellLongnonpolya, "#{base}/wgencoderikencagealignmentsh1hesccelllongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsHuvecCytosolLongnonpolya, "#{base}/wgencoderikencagealignmentshuveccytosollongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsHepg2CytosolLongnonpolya, "#{base}/wgencoderikencagealignmentshepg2cytosollongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsHepg2NucleusLongnonpolya, "#{base}/wgencoderikencagealignmentshepg2nucleuslongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsHepg2NucleolusTotal, "#{base}/wgencoderikencagealignmentshepg2nucleolustotal"
      autoload :WgEncodeRikenCageAlignmentsK562PolysomeLongnonpolya, "#{base}/wgencoderikencagealignmentsk562polysomelongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsNhekCytosolLongnonpolya, "#{base}/wgencoderikencagealignmentsnhekcytosollongnonpolya"
      autoload :WgEncodeRikenCageAlignmentsNhekNucleusLongnonpolya, "#{base}/wgencoderikencagealignmentsnheknucleuslongnonpolya"
