#!/usr/local/bin/ruby-1.9

require 'erb'
require 'fileutils'

TABLES = %w(
wgEncodeUwAffyExonArrayGm12878SimpleSignalRep1
wgEncodeUwAffyExonArrayK562SimpleSignalRep1
wgEncodeUwAffyExonArrayK562SimpleSignalRep2
wgEncodeUwAffyExonArrayHelas3SimpleSignalRep1
wgEncodeUwAffyExonArrayHelas3SimpleSignalRep2
wgEncodeUwAffyExonArrayHepg2SimpleSignalRep1
wgEncodeUwAffyExonArrayHepg2SimpleSignalRep2
wgEncodeUwAffyExonArrayHuvecSimpleSignalRep1
wgEncodeUwAffyExonArrayHuvecSimpleSignalRep2
wgEncodeUwAffyExonArrayA549SimpleSignalRep1
wgEncodeUwAffyExonArrayA549SimpleSignalRep2
wgEncodeUwAffyExonArrayAg04449SimpleSignalRep1
wgEncodeUwAffyExonArrayAg04449SimpleSignalRep2
wgEncodeUwAffyExonArrayAg04450SimpleSignalRep1 
wgEncodeUwAffyExonArrayAg04450SimpleSignalRep2
wgEncodeUwAffyExonArrayAg09309SimpleSignalRep1
wgEncodeUwAffyExonArrayAg09309SimpleSignalRep2
wgEncodeUwAffyExonArrayAg09319SimpleSignalRep1
wgEncodeUwAffyExonArrayAg09319SimpleSignalRep2
wgEncodeUwAffyExonArrayAg10803SimpleSignalRep1
wgEncodeUwAffyExonArrayAg10803SimpleSignalRep2 
wgEncodeUwAffyExonArrayAoafSimpleSignalRep1
wgEncodeUwAffyExonArrayAoafSimpleSignalRep2
wgEncodeUwAffyExonArrayBe2cSimpleSignalRep1
wgEncodeUwAffyExonArrayBe2cSimpleSignalRep2
wgEncodeUwAffyExonArrayBjSimpleSignalRep1
wgEncodeUwAffyExonArrayBjSimpleSignalRep2
wgEncodeUwAffyExonArrayCmkSimpleSignalRep1
wgEncodeUwAffyExonArrayCaco2SimpleSignalRep1 
wgEncodeUwAffyExonArrayCaco2SimpleSignalRep2
wgEncodeUwAffyExonArrayGm06990SimpleSignalRep1
wgEncodeUwAffyExonArrayGm06990SimpleSignalRep2
wgEncodeUwAffyExonArrayH7esSimpleSignalRep1
wgEncodeUwAffyExonArrayH7esSimpleSignalRep2
wgEncodeUwAffyExonArrayHaspSimpleSignalRep1
wgEncodeUwAffyExonArrayHaspSimpleSignalRep2
wgEncodeUwAffyExonArrayHaeSimpleSignalRep1
wgEncodeUwAffyExonArrayHaeSimpleSignalRep2
wgEncodeUwAffyExonArrayHacSimpleSignalRep1
wgEncodeUwAffyExonArrayHacSimpleSignalRep2
wgEncodeUwAffyExonArrayHbmecSimpleSignalRep1
wgEncodeUwAffyExonArrayHbmecSimpleSignalRep2
wgEncodeUwAffyExonArrayHcfSimpleSignalRep1
wgEncodeUwAffyExonArrayHcfSimpleSignalRep2
wgEncodeUwAffyExonArrayHcfaaSimpleSignalRep1
wgEncodeUwAffyExonArrayHcfaaSimpleSignalRep2
wgEncodeUwAffyExonArrayHcmSimpleSignalRep1
wgEncodeUwAffyExonArrayHcmSimpleSignalRep2
wgEncodeUwAffyExonArrayHconfSimpleSignalRep1
wgEncodeUwAffyExonArrayHconfSimpleSignalRep2
wgEncodeUwAffyExonArrayHcpeSimpleSignalRep1
wgEncodeUwAffyExonArrayHcpeSimpleSignalRep2
wgEncodeUwAffyExonArrayHct116SimpleSignalRep1
wgEncodeUwAffyExonArrayHct116SimpleSignalRep2
wgEncodeUwAffyExonArrayHeeSimpleSignalRep1
wgEncodeUwAffyExonArrayHeeSimpleSignalRep2
wgEncodeUwAffyExonArrayHek293SimpleSignalRep1
wgEncodeUwAffyExonArrayHek293SimpleSignalRep2
wgEncodeUwAffyExonArrayHgfSimpleSignalRep1
wgEncodeUwAffyExonArrayHgfSimpleSignalRep2
wgEncodeUwAffyExonArrayHipeSimpleSignalRep1
wgEncodeUwAffyExonArrayHipeSimpleSignalRep2
wgEncodeUwAffyExonArrayHl60SimpleSignalRep1
wgEncodeUwAffyExonArrayHl60SimpleSignalRep2
wgEncodeUwAffyExonArrayHmecSimpleSignalRep1
wgEncodeUwAffyExonArrayHmecSimpleSignalRep2
wgEncodeUwAffyExonArrayHmfSimpleSignalRep1
wgEncodeUwAffyExonArrayHmfSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecllySimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecllySimpleSignalRep2
wgEncodeUwAffyExonArrayHmveclblSimpleSignalRep1
wgEncodeUwAffyExonArrayHmveclblSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecdbladSimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecdbladSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecdblneoSimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecdblneoSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecdlyadSimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecdlyadSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecdlyneoSimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecdlyneoSimpleSignalRep2
wgEncodeUwAffyExonArrayHmvecdneoSimpleSignalRep1
wgEncodeUwAffyExonArrayHmvecdneoSimpleSignalRep2
wgEncodeUwAffyExonArrayHnpceSimpleSignalRep1
wgEncodeUwAffyExonArrayHnpceSimpleSignalRep2
wgEncodeUwAffyExonArrayHpafSimpleSignalRep1
wgEncodeUwAffyExonArrayHpafSimpleSignalRep2
wgEncodeUwAffyExonArrayHpfSimpleSignalRep1
wgEncodeUwAffyExonArrayHpfSimpleSignalRep2
wgEncodeUwAffyExonArrayHpdlfSimpleSignalRep1
wgEncodeUwAffyExonArrayHpdlfSimpleSignalRep2
wgEncodeUwAffyExonArrayHrceSimpleSignalRep1
wgEncodeUwAffyExonArrayHrceSimpleSignalRep2
wgEncodeUwAffyExonArrayHreSimpleSignalRep1
wgEncodeUwAffyExonArrayHreSimpleSignalRep2
wgEncodeUwAffyExonArrayHrgecSimpleSignalRep1
wgEncodeUwAffyExonArrayHrgecSimpleSignalRep2
wgEncodeUwAffyExonArrayHrpeSimpleSignalRep1
wgEncodeUwAffyExonArrayHrpeSimpleSignalRep2
wgEncodeUwAffyExonArrayHsmmSimpleSignalRep1
wgEncodeUwAffyExonArrayHsmmSimpleSignalRep2
wgEncodeUwAffyExonArrayHsmmtSimpleSignalRep1
wgEncodeUwAffyExonArrayHvmfSimpleSignalRep1
wgEncodeUwAffyExonArrayHvmfSimpleSignalRep2
wgEncodeUwAffyExonArrayJurkatSimpleSignalRep1
wgEncodeUwAffyExonArrayJurkatSimpleSignalRep2
wgEncodeUwAffyExonArrayLncapSimpleSignalRep1
wgEncodeUwAffyExonArrayLncapSimpleSignalRep2
wgEncodeUwAffyExonArrayMcf7SimpleSignalRep1
wgEncodeUwAffyExonArrayMcf7SimpleSignalRep2
wgEncodeUwAffyExonArrayNb4SimpleSignalRep1
wgEncodeUwAffyExonArrayNb4SimpleSignalRep2 
wgEncodeUwAffyExonArrayNhaSimpleSignalRep1
wgEncodeUwAffyExonArrayNhaSimpleSignalRep2
wgEncodeUwAffyExonArrayNhdfadSimpleSignalRep1
wgEncodeUwAffyExonArrayNhdfadSimpleSignalRep2
wgEncodeUwAffyExonArrayNhdfneoSimpleSignalRep1
wgEncodeUwAffyExonArrayNhdfneoSimpleSignalRep2
wgEncodeUwAffyExonArrayNhekSimpleSignalRep1
wgEncodeUwAffyExonArrayNhlfSimpleSignalRep1
wgEncodeUwAffyExonArrayNhlfSimpleSignalRep2
wgEncodeUwAffyExonArrayPanc1SimpleSignalRep1
wgEncodeUwAffyExonArrayPanc1SimpleSignalRep2
wgEncodeUwAffyExonArrayRptecSimpleSignalRep1
wgEncodeUwAffyExonArrayRptecSimpleSignalRep2
wgEncodeUwAffyExonArraySaecSimpleSignalRep1
wgEncodeUwAffyExonArraySaecSimpleSignalRep2
wgEncodeUwAffyExonArraySkmcSimpleSignalRep1
wgEncodeUwAffyExonArraySkmcSimpleSignalRep2
wgEncodeUwAffyExonArraySknshraSimpleSignalRep1
wgEncodeUwAffyExonArraySknshraSimpleSignalRep2
wgEncodeUwAffyExonArrayTh1SimpleSignalRep1
wgEncodeUwAffyExonArrayWi38SimpleSignalRep1
wgEncodeUwAffyExonArrayWi38SimpleSignalRep2
wgEncodeUwAffyExonArrayWi38OhtamSimpleSignalRep1
wgEncodeUwAffyExonArrayWi38OhtamSimpleSignalRep2
)

temp_spec = "template_spec.txt"
temp_auto = "template_auto.txt"
temp_main = "template_main.txt"

FileUtils.mkdir_p("Specs") unless FileTest.exist?("Specs")
FileUtils.mkdir_p("Scripts") unless FileTest.exist?("Scripts")

TABLES.each do |tab|
  table_name  = tab
  klass_name  = tab[0].upcase << tab[1..-1]
  script_name = tab.downcase

  open("Specs/#{script_name}_spec.rb", "w") do |writer|
    erb = ERB.new File.read(temp_spec)
    writer.puts erb.result binding
  end

  open("Scripts/#{script_name}.rb", "w") do |writer|
    erb = ERB.new File.read(temp_main)
    writer.puts erb.result binding
  end

end

open("autoload_snippet.rb", 'w') do |writer|
  writer.puts "## track: UW Affy Exon"
  TABLES.each do |tab|
    table_name  = tab
    klass_name  = tab[0].upcase << tab[1..-1]
    script_name = tab.downcase
    erb = ERB.new File.read(temp_auto)
    writer.puts erb.result binding
  end
end
