#!/usr/local/bin/ruby-1.9

require 'erb'
require 'fileutils'

# tables "*Sig" and "*OverlapSignal" are pointer tables containing
# single records. These are ommited.

TABLES = %w(
wgEncodeUwDnaseGm12878HotspotsRep1
wgEncodeUwDnaseGm12878PkRep1
wgEncodeUwDnaseGm12878HotspotsRep2
wgEncodeUwDnaseGm12878PkRep2
wgEncodeUwDnaseH1hescHotspotsRep1
wgEncodeUwDnaseH1hescPkRep1
wgEncodeUwDnaseK562HotspotsRep1
wgEncodeUwDnaseK562PkRep1
wgEncodeUwDnaseK562HotspotsRep2
wgEncodeUwDnaseK562PkRep2
wgEncodeUwDnaseHelas3HotspotsRep1
wgEncodeUwDnaseHelas3PkRep1
wgEncodeUwDnaseHelas3HotspotsRep2
wgEncodeUwDnaseHelas3PkRep2
wgEncodeUwDnaseHepg2HotspotsRep1
wgEncodeUwDnaseHepg2PkRep1
wgEncodeUwDnaseHepg2HotspotsRep2
wgEncodeUwDnaseHepg2PkRep2
wgEncodeUwDnaseHuvecHotspotsRep1
wgEncodeUwDnaseHuvecPkRep1
wgEncodeUwDnaseAg04449HotspotsRep1
wgEncodeUwDnaseAg04449PkRep1
wgEncodeUwDnaseAg04449HotspotsRep2
wgEncodeUwDnaseAg04449PkRep2
wgEncodeUwDnaseAg04450HotspotsRep1
wgEncodeUwDnaseAg04450PkRep1
wgEncodeUwDnaseAg04450HotspotsRep2
wgEncodeUwDnaseAg04450PkRep2
wgEncodeUwDnaseAg09309HotspotsRep1
wgEncodeUwDnaseAg09309PkRep1
wgEncodeUwDnaseAg09309HotspotsRep2
wgEncodeUwDnaseAg09309PkRep2
wgEncodeUwDnaseAg09319HotspotsRep1
wgEncodeUwDnaseAg09319PkRep1
wgEncodeUwDnaseAg09319HotspotsRep2
wgEncodeUwDnaseAg09319PkRep2
wgEncodeUwDnaseAg10803HotspotsRep1
wgEncodeUwDnaseAg10803PkRep1
wgEncodeUwDnaseAg10803HotspotsRep2
wgEncodeUwDnaseAg10803PkRep2
wgEncodeUwDnaseAoafHotspotsRep1
wgEncodeUwDnaseAoafPkRep1
wgEncodeUwDnaseAoafHotspotsRep2
wgEncodeUwDnaseAoafPkRep2
wgEncodeUwDnaseBjHotspotsRep1
wgEncodeUwDnaseBjPkRep1
wgEncodeUwDnaseBjHotspotsRep2
wgEncodeUwDnaseBjPkRep2
wgEncodeUwDnaseCaco2HotspotsRep1
wgEncodeUwDnaseCaco2PkRep1
wgEncodeUwDnaseCaco2HotspotsRep2
wgEncodeUwDnaseCaco2PkRep2
wgEncodeUwDnaseCmkHotspotsRep1
wgEncodeUwDnaseCmkPkRep1
wgEncodeUwDnaseGm06990HotspotsRep1
wgEncodeUwDnaseGm06990PkRep1
wgEncodeUwDnaseGm06990HotspotsRep2
wgEncodeUwDnaseGm06990PkRep2
wgEncodeUwDnaseGm12865HotspotsRep1
wgEncodeUwDnaseGm12865PkRep1
wgEncodeUwDnaseGm12865HotspotsRep2
wgEncodeUwDnaseGm12865PkRep2
wgEncodeUwDnaseH7esHotspotsRep1
wgEncodeUwDnaseH7esPkRep1
wgEncodeUwDnaseH7esHotspotsRep2
wgEncodeUwDnaseH7esPkRep2
wgEncodeUwDnaseHaeHotspotsRep1
wgEncodeUwDnaseHaePkRep1
wgEncodeUwDnaseHaeHotspotsRep2
wgEncodeUwDnaseHaePkRep2
wgEncodeUwDnaseHbmecHotspotsRep1
wgEncodeUwDnaseHbmecPkRep1 
wgEncodeUwDnaseHbmecHotspotsRep2
wgEncodeUwDnaseHbmecPkRep2
wgEncodeUwDnaseHcfHotspotsRep1
wgEncodeUwDnaseHcfPkRep1
wgEncodeUwDnaseHcfHotspotsRep2
wgEncodeUwDnaseHcfPkRep2
wgEncodeUwDnaseHcfaaHotspotsRep1
wgEncodeUwDnaseHcfaaPkRep1
wgEncodeUwDnaseHcfaaHotspotsRep2
wgEncodeUwDnaseHcfaaPkRep2
wgEncodeUwDnaseHcmHotspotsRep1
wgEncodeUwDnaseHcmPkRep1
wgEncodeUwDnaseHcmHotspotsRep2
wgEncodeUwDnaseHcmPkRep2
wgEncodeUwDnaseHconfHotspotsRep1
wgEncodeUwDnaseHconfPkRep1
wgEncodeUwDnaseHconfHotspotsRep2
wgEncodeUwDnaseHconfPkRep2
wgEncodeUwDnaseHcpeHotspotsRep1
wgEncodeUwDnaseHcpePkRep1
wgEncodeUwDnaseHcpeHotspotsRep2
wgEncodeUwDnaseHcpePkRep2
wgEncodeUwDnaseHct116HotspotsRep1
wgEncodeUwDnaseHct116PkRep1
wgEncodeUwDnaseHct116HotspotsRep2
wgEncodeUwDnaseHct116PkRep2 
wgEncodeUwDnaseHeeHotspotsRep1
wgEncodeUwDnaseHeePkRep1
wgEncodeUwDnaseHeeHotspotsRep2
wgEncodeUwDnaseHeePkRep2
wgEncodeUwDnaseHgfHotspotsRep1
wgEncodeUwDnaseHgfPkRep1
wgEncodeUwDnaseHgfHotspotsRep2
wgEncodeUwDnaseHgfPkRep2
wgEncodeUwDnaseHl60HotspotsRep1
wgEncodeUwDnaseHl60PkRep1 
wgEncodeUwDnaseHl60HotspotsRep2
wgEncodeUwDnaseHl60PkRep2
wgEncodeUwDnaseHmecHotspotsRep1
wgEncodeUwDnaseHmecPkRep1
wgEncodeUwDnaseHmecHotspotsRep2
wgEncodeUwDnaseHmecPkRep2
wgEncodeUwDnaseHmfHotspotsRep1
wgEncodeUwDnaseHmfPkRep1
wgEncodeUwDnaseHmfHotspotsRep2 
wgEncodeUwDnaseHmfPkRep2 
wgEncodeUwDnaseHmvecllyHotspotsRep1
wgEncodeUwDnaseHmvecllyPkRep1
wgEncodeUwDnaseHmvecllyHotspotsRep2
wgEncodeUwDnaseHmvecllyPkRep2
wgEncodeUwDnaseHmveclblHotspotsRep1
wgEncodeUwDnaseHmveclblPkRep1
wgEncodeUwDnaseHmveclblHotspotsRep2
wgEncodeUwDnaseHmveclblPkRep2
wgEncodeUwDnaseHmvecdbladHotspotsRep1
wgEncodeUwDnaseHmvecdbladPkRep1
wgEncodeUwDnaseHmvecdbladHotspotsRep2
wgEncodeUwDnaseHmvecdbladPkRep2 
wgEncodeUwDnaseHmvecdblneoHotspotsRep1
wgEncodeUwDnaseHmvecdblneoPkRep1
wgEncodeUwDnaseHmvecdblneoHotspotsRep2
wgEncodeUwDnaseHmvecdblneoPkRep2
wgEncodeUwDnaseHmvecdlyadHotspotsRep1
wgEncodeUwDnaseHmvecdlyadPkRep1
wgEncodeUwDnaseHmvecdlyadHotspotsRep2
wgEncodeUwDnaseHmvecdlyadPkRep2
wgEncodeUwDnaseHmvecdlyneoHotspotsRep1
wgEncodeUwDnaseHmvecdlyneoPkRep1
wgEncodeUwDnaseHmvecdlyneoHotspotsRep2
wgEncodeUwDnaseHmvecdlyneoPkRep2
wgEncodeUwDnaseHmvecdneoHotspotsRep1
wgEncodeUwDnaseHmvecdneoPkRep1
wgEncodeUwDnaseHmvecdneoHotspotsRep2
wgEncodeUwDnaseHmvecdneoPkRep2
wgEncodeUwDnaseHnpceHotspotsRep1
wgEncodeUwDnaseHnpcePkRep1
wgEncodeUwDnaseHnpceHotspotsRep2
wgEncodeUwDnaseHnpcePkRep2
wgEncodeUwDnaseHpafHotspotsRep1
wgEncodeUwDnaseHpafPkRep1
wgEncodeUwDnaseHpafHotspotsRep2
wgEncodeUwDnaseHpafPkRep2
wgEncodeUwDnaseHpfHotspotsRep1
wgEncodeUwDnaseHpfPkRep1
wgEncodeUwDnaseHpfHotspotsRep2
wgEncodeUwDnaseHpfPkRep2
wgEncodeUwDnaseHpdlfHotspotsRep1
wgEncodeUwDnaseHpdlfPkRep1
wgEncodeUwDnaseHpdlfHotspotsRep2
wgEncodeUwDnaseHpdlfPkRep2
wgEncodeUwDnaseHrceHotspotsRep1
wgEncodeUwDnaseHrcePkRep1
wgEncodeUwDnaseHrceHotspotsRep2
wgEncodeUwDnaseHrcePkRep2
wgEncodeUwDnaseHreHotspotsRep1
wgEncodeUwDnaseHrePkRep1
wgEncodeUwDnaseHreHotspotsRep2
wgEncodeUwDnaseHrePkRep2
wgEncodeUwDnaseHrpeHotspotsRep1
wgEncodeUwDnaseHrpePkRep1
wgEncodeUwDnaseHrpeHotspotsRep2
wgEncodeUwDnaseHrpePkRep2
wgEncodeUwDnaseHvmfHotspotsRep1
wgEncodeUwDnaseHvmfPkRep1
wgEncodeUwDnaseHvmfHotspotsRep2
wgEncodeUwDnaseHvmfPkRep2
wgEncodeUwDnaseMcf7HotspotsRep1
wgEncodeUwDnaseMcf7PkRep1
wgEncodeUwDnaseMcf7HotspotsRep2
wgEncodeUwDnaseMcf7PkRep2
wgEncodeUwDnaseNb4HotspotsRep1
wgEncodeUwDnaseNb4PkRep1
wgEncodeUwDnaseNb4HotspotsRep2
wgEncodeUwDnaseNb4PkRep2
wgEncodeUwDnaseNhaHotspotsRep1
wgEncodeUwDnaseNhaPkRep1
wgEncodeUwDnaseNhaHotspotsRep2
wgEncodeUwDnaseNhaPkRep2
wgEncodeUwDnaseNhdfadHotspotsRep1
wgEncodeUwDnaseNhdfadPkRep1
wgEncodeUwDnaseNhdfadHotspotsRep2
wgEncodeUwDnaseNhdfadPkRep2
wgEncodeUwDnaseNhdfneoHotspotsRep1
wgEncodeUwDnaseNhdfneoPkRep1
wgEncodeUwDnaseNhdfneoHotspotsRep2
wgEncodeUwDnaseNhdfneoPkRep2
wgEncodeUwDnaseNhekHotspotsRep1
wgEncodeUwDnaseNhekPkRep1
wgEncodeUwDnaseNhlfHotspotsRep1
wgEncodeUwDnaseNhlfPkRep1
wgEncodeUwDnaseNhlfHotspotsRep2
wgEncodeUwDnaseNhlfPkRep2
wgEncodeUwDnasePanc1HotspotsRep1
wgEncodeUwDnasePanc1PkRep1
wgEncodeUwDnasePanc1HotspotsRep2
wgEncodeUwDnasePanc1PkRep2
wgEncodeUwDnaseSaecHotspotsRep1
wgEncodeUwDnaseSaecPkRep1
wgEncodeUwDnaseSaecHotspotsRep2
wgEncodeUwDnaseSaecPkRep2 
wgEncodeUwDnaseSkmcHotspotsRep1
wgEncodeUwDnaseSkmcPkRep1
wgEncodeUwDnaseSkmcHotspotsRep2
wgEncodeUwDnaseSkmcPkRep2
wgEncodeUwDnaseSknshraHotspotsRep1
wgEncodeUwDnaseSknshraPkRep1
wgEncodeUwDnaseSknshraHotspotsRep2
wgEncodeUwDnaseSknshraPkRep2
wgEncodeUwDnaseTh1HotspotsRep1
wgEncodeUwDnaseTh1PkRep1
wgEncodeUwDnaseTh2HotspotsRep1
wgEncodeUwDnaseTh2PkRep1
)

temp_spec = "template_spec.txt"
temp_auto = "template_auto.txt"
temp_main = "template_main.txt"

FileUtils.mkdir_p("Specs") unless FileTest.exist?("Specs")
FileUtils.mkdir_p("Scripts") unless FileTest.exist?("Scripts")

TABLES.each do |tab|
  table_name  = tab
  klass_name  = tab[0].upcase << tab[1..-1]
  script_name = tab.downcase

  open("Specs/#{script_name}_spec.rb", "w") do |writer|
    erb = ERB.new File.read(temp_spec)
    writer.puts erb.result binding
  end

  open("Scripts/#{script_name}.rb", "w") do |writer|
    erb = ERB.new File.read(temp_main)
    writer.puts erb.result binding
  end

end

open("autoload_snippet.rb", 'w') do |writer|
  writer.puts "      ## track: UW DNaseI HS"
  TABLES.each do |tab|
    table_name  = tab
    klass_name  = tab[0].upcase << tab[1..-1]
    script_name = tab.downcase
    erb = ERB.new File.read(temp_auto)
    writer.puts erb.result binding
  end
end
