      ## track: EGASP Update
      autoload :EncodeEgaspUpdAugustusAbinitio, "#{base}/encodeegaspupdaugustusabinitio"
      autoload :EncodeEgaspUpdAugustusEst, "#{base}/encodeegaspupdaugustusest"
      autoload :EncodeEgaspUpdAugustusDual, "#{base}/encodeegaspupdaugustusdual"
      autoload :EncodeEgaspUpdAugustusAny, "#{base}/encodeegaspupdaugustusany"
      autoload :EncodeEgaspUpdExogean, "#{base}/encodeegaspupdexogean"
      autoload :EncodeEgaspUpdFgenesh, "#{base}/encodeegaspupdfgenesh"
      autoload :EncodeEgaspUpdGeneId, "#{base}/encodeegaspupdgeneid"
      autoload :EncodeEgaspUpdGeneIdU12, "#{base}/encodeegaspupdgeneidu12"
      autoload :EncodeEgaspUpdJigsaw, "#{base}/encodeegaspupdjigsaw"
      autoload :EncodeEgaspUpdSgp2, "#{base}/encodeegaspupdsgp2"
      autoload :EncodeEgaspUpdSgp2U12, "#{base}/encodeegaspupdsgp2u12"
      autoload :EncodeEgaspUpdYalePseudo, "#{base}/encodeegaspupdyalepseudo"
